PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?iri
WHERE {
    GRAPH <http://example.org/HPO> {
        ?iri rdfs:label 'VAR_PHENOTYPE_NAME' .
    }
}