services:
  jupyter-book:
    image: ejp-rd-jupyter-book
    build:
      context: .
      dockerfile_inline: |
        FROM quay.io/jupyter/base-notebook
        USER root
        ARG DEBIAN_FRONTEND=noninteractive
        RUN apt-get update && apt-get -qq install \
          curl \
          jq \
          texlive-latex-extra \
          texlive-fonts-extra \
          texlive-xetex latexmk
        USER jovyan
        COPY requirements.txt /requirements.txt
        RUN pip install -r /requirements.txt
        RUN pip install jupyter-server-proxy
    ports:
      - ${JUPYTER_PORT:-8888}:8888
    userns_mode: keep-id:uid=1000,gid=100
    working_dir: /home/jovyan/work/
    environment:
      - NOTEBOOK_ARGS=--NotebookApp.token='${JUPYTER_PASS:-password}'
    container_name: notebook
    volumes:
      - ${JUPYTER_BOOK_SRC:-./}:/home/jovyan/work/:rw
    configs:
      - source: shortcuts.jupyterlab-settings
        target: /opt/conda/share/jupyter/lab/settings/overrides.json
      - source: jupyter_server_config.py
        target: /home/jovyan/.jupyter/jupyter_server_config.py

configs:
  shortcuts.jupyterlab-settings:
    content: |
      {
          "@jupyterlab/shortcuts-extension:shortcuts": {
              "shortcuts": [
                  {
                      "args": {},
                      "command": "inline-completer:next",
                      "keys": [
                          "Alt ]"
                      ],
                      "selector": ".jp-mod-completer-enabled",
                      "disabled": true
                  },
                  {
                      "args": {},
                      "command": "inline-completer:previous",
                      "keys": [
                          "Alt ["
                      ],
                      "selector": ".jp-mod-completer-enabled",
                      "disabled": true
                  }
              ]
          }
      }
  jupyter_server_config.py:
    content: |
      c.ServerProxy.servers = {
          "jupyter-book": {
              "command": [
                  "python3", "-m", "http.server", "{port}",
                  "-d", "/home/jovyan/work/_build/html/"
                ],
              "absolute_url": False,
              "new_browser_tab": True
          }
      }